### ISSUE TITLE
Can't call an exposed library's function that was originally "external"

### ISSUE THREAD

**Issue by cj-l** [frangio/hardhat-exposed#5]
I have a library with an external function, but when I get the exposed version I'm only able to call the newly created external functions, and not those that were external in the original library.

I guess this is because libraries can't inherit? Any solution here?

Many thanks

**Comment by frangio** [comment]
Should be fixed in https://github.com/frangio/hardhat-exposed/commit/6c2e61199cd38a124bcaebf3f0c16036c3b922cb. Please try out the new verison.
