### ISSUE TITLE
Incompatible with Typechain

### ISSUE THREAD

**Issue by ItsNickBarry** [frangio/hardhat-exposed#9]
I am getting this error when using this plugin in combination with `@hardhat/typechain`:

> `Error: EEXIST: file already exists, mkdir '/home/nickbarry/workspace/abdk-math-utils/contracts-exposed/Contract.sol'`

It's fixed by setting a different `prefix` in the `exposed` config, such as `x` or `_`.

This may be a typechain issue (in fact, the stack trace points to typechain files), but I couldn't reproduce with typechain alone by adding the `$` character to contract names.  Need to better understand the context before reporting to them.

**Comment by ItsNickBarry** [comment]
It seems like the `$` prefix works if compilation has already been run and the most recent compilation used a different prefix.

1. `hardhat clean && rm -rf typechain-types`
3. compile with `$` prefix => error
1. compile with `_` prefix => okay
2. compile with `$` prefix => okay
3. compile with `$` prefix => error
4. compile with `_` prefix => okay
5. compile with `$` prefix => okay

**Comment by frangio** [comment]
I wasn't able to reproduce this. Could you submit a repository with reproduction?

**Comment by ItsNickBarry** [comment]
Could be an OS issue?  Using Ubuntu 20.04.  Node 16.13.1.

___

Can reproduce in this repository: https://github.com/ItsNickBarry/hardhat-waffle-template

Add this contract:
```solidity
contract Test {
    function fnExternal() external pure returns (uint256) {
        return fnInternal();
    }

    function fnInternal() internal pure returns (uint256) {
        return 12;
    }
}
```

Install with yarn: `yarn add --dev hardhat-exposed`

Add import to HH config.

**Comment by frangio** [comment]
Thanks. It's not the prefix. There's something else going wrong. I'll open an issue and see if the TypeChain team can identify the problem.

**Comment by ndavd** [comment]
Any updates on this?

**Comment by frangio** [comment]
These plugins still don't work together. hardhat-exposed seems to do something that is unexpected for Typechain and causes it to fail. I don't understand Typechain internals in order to suggest a fix.

**Comment by ItsNickBarry** [comment]
I found the problem and opened a PR: https://github.com/dethcrypto/TypeChain/pull/908.  It won't be merged because Typechain is deprecated.

I think the linked issue above is unrelated.
